sequenceDiagram
    participant U as User (Filter)
    participant P1 as Pipe 1 (Input Data)
    participant AS as Authentication Service (Filter)
    participant DB as Database (Sink/Source)
    participant P2 as Pipe 2 (Email Info)
    participant ES as Emailer Service (Filter)
    participant P3 as Pipe 3 (Email Data)
    participant R as Resend Service (Data Sink)

    P1->>+U: Registers (email, username, password)
    P1->>+AS: Passes Registration Data
    AS->>+AS: Read
    AS->>+DB: Save User Data
    DB-->>-AS: Confirmation
    AS->>+P2: Prepare Email Info
    P2->>+P2: Read
    P2->>+ES: Passes Email Info
    P3->>+ES: Reads Email Info With Template
    P3->>+P3: Read
    P3->>+R: Passes Email Info With Template
    R-->>-AS: Email Sent
    AS-->>-U: Registration Complete (Account + Verify Email Sent)
