FROM maven:3.8.6-jdk-8-slim AS builder
WORKDIR /app
COPY . .
RUN mvn clean package

FROM tomcat:8-jdk8-openjdk
RUN rm -rf /usr/local/tomcat/webapps/*
COPY --from=builder /app/target/soa-task-1.0-SNAPSHOT.war /usr/local/tomcat/webapps/ROOT.war
EXPOSE 8080
CMD ["catalina.sh", "run"]
